/* ==========================================================================
   Generated Domain Contracts & DTO Schemas
   Feature: Shipping Quote Calculation
   Architecture: Hexagonal Architecture (Ports & Adapters)
   Stack: csharp + dotnet10 + efcore
   Generated by gherkin-ai CLI v1.5.0
   ========================================================================== */

import { z } from 'zod';

// --------------------------------------------------------------------------
// 1. Domain Event Interfaces
// --------------------------------------------------------------------------
export interface IDomainEvent {
  eventId: string;
  occurredOn: Date;
  eventType: string;
}



// --------------------------------------------------------------------------
// 2. Command DTO Schemas (Zod Validation)
// --------------------------------------------------------------------------
export const ShippingQuoteCalculationCommandSchema = z.object({
  requestId: z.string().uuid(),
  timestamp: z.string().datetime(),
  payload: z.record(z.unknown())
});

export type ShippingQuoteCalculationCommand = z.infer<typeof ShippingQuoteCalculationCommandSchema>;

// --------------------------------------------------------------------------
// 3. Domain Repository Port (Outbound Interface)
// --------------------------------------------------------------------------
export interface IShippingQuoteCalculationRepository {
  findById(id: string): Promise<unknown | null>;
  save(entity: unknown): Promise<void>;
  delete(id: string): Promise<void>;
}

// --------------------------------------------------------------------------
// 4. Application Event Publisher Port
// --------------------------------------------------------------------------
export interface IEventPublisher {
  publish(event: IDomainEvent): Promise<void>;
}
