version: '3.8'

services:
  # Database Service
  postgresql:
    image: postgres:16-alpine
    container_name: delivery_app-db
    restart: always
    environment:
      POSTGRES_DB: delivery_app_db
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Message Broker
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: delivery_app-mq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: delivery_app-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
