/* ==========================================================================
   Generated Test Fixtures & Seed Setup
   Feature: Shipping Quote Calculation
   Generated by gherkin-ai CLI v1.0.0
   ========================================================================== */

import bcrypt from 'bcrypt';

export interface TestUserFixture {
  id: string;
  email: string;
  passwordRaw: string;
  passwordHash: string;
  role: string;
  isActive: boolean;
}

export async function createTestUserFixture(): Promise<TestUserFixture> {
  const saltRounds = 12;
  const passwordRaw = 'Pass123!';
  const passwordHash = await bcrypt.hash(passwordRaw, saltRounds);

  return {
    id: 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
    email: 'dev@example.com',
    passwordRaw,
    passwordHash,
    role: 'ADMIN',
    isActive: true
  };
}

export const GHERKIN_GIVEN_PRECONDITIONS = [
  "a customer with ID \"cust-001\"",
  "a shipment with actual weight 2.0 kg",
  "a shipment with actual weight 5.0 kg"
];
